language: csharp
solution: ApiExample.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore ApiExample.sln
after_script:
  - xbuild ./src/ApiExample.sln
  - nunit-console NUnitTestProject1/bin/Release/NUnitTestProject1.dll
