language: csharp
mono: latest
dotnet: 3.1.200
before_install:
  - sudo apt-get install nunit-console
script:
  - dotnet restore
  - msbuild
  - dotnet test ../NUnitTestProject1/bin/Debug/netcoreapp3.1/NUnitTestProject1.dll
